# Generated by Django 6.0.5 on 2026-06-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_founder'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Contemporary Dance & Theatre · Toronto, Canada', max_length=200)),
                ('hero_tagline', models.CharField(blank=True, default='Work that lives in the body.\nQuestions the archive refuses.', max_length=300)),
                ('dark_band_heading', models.CharField(default='Work that refuses to settle', max_length=200)),
                ('dark_band_body', models.TextField(blank=True, default="the– hOle –studio is an independent dance, performance, and film company founded by Iranian artists Jaber Ramezan and Negar Nemati, based in Toronto. Building on more than fifteen years of practice, the studio develops original works that move between disciplines, cultures, and performance traditions.\n\nThe studio is available for presentations, co-productions, and residencies. If you're a festival, presenter, or venue — we'd like to hear from you.")),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
        migrations.CreateModel(
            name='HomePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/strip/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
