# Generated by Django 6.0.5 on 2026-06-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homepage_homephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='logo',
            field=models.ImageField(blank=True, help_text='Nav logo image. Leave blank to use text.', null=True, upload_to='site/'),
        ),
    ]
