# Generated by Django 6.0 on 2026-06-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_homepage_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_quote', models.CharField(default='"We believe that every project demands its own form."', max_length=300)),
                ('header_intro', models.TextField(blank=True, default='the– hOle –studio is an independent dance, performance, and film company founded by Iranian artists Jaber Ramezan and Negar Nemati, based in Toronto. The studio develops original works that move between disciplines, cultures, and performance traditions.')),
                ('stat1_num', models.CharField(default='15+', max_length=20)),
                ('stat1_label', models.CharField(default='Years of Practice', max_length=100)),
                ('stat2_num', models.CharField(default='3', max_length=20)),
                ('stat2_label', models.CharField(default='Productions', max_length=100)),
                ('stat3_num', models.CharField(default='3', max_length=20)),
                ('stat3_label', models.CharField(default='Countries', max_length=100)),
                ('story_body', models.TextField(blank=True, default="the– hOle –studio is an independent dance, performance, and film company founded by Iranian artists Jaber Ramezan and Negar Nemati. Building on more than fifteen years of artistic practice across theatre, dance, film, and design, the studio develops original works that move between disciplines, cultures, and performance traditions.\n\nRooted in the experimental spirit of Tehran's independent arts scene and shaped by international collaborations across Europe and North America, the company brings together artists, performers, filmmakers, and designers to create contemporary works for stage and screen.\n\nLed by Artistic Director Jaber Ramezan, the studio is driven by a search for new forms of performance and storytelling. Its projects emerge through research, collaboration, and experimentation, often crossing the boundaries between theatre, choreography, cinema, and visual design.")),
                ('land_acknowledgement', models.TextField(blank=True, default='the– hOle –studio acknowledges that our work takes place on the traditional territories of many Indigenous Nations, including the Wendat, the Anishinaabeg, the Mississaugas of the Credit First Nation, and the Haudenosaunee Confederacy. We recognize their enduring presence, stewardship, and relationships to this land, and we are committed to ongoing learning, respect, and meaningful dialogue.')),
                ('value1_label', models.CharField(default='Form First', max_length=100)),
                ('value1_text', models.TextField(blank=True, default='We believe that every project demands its own form. Rather than working within fixed genres or disciplines, we approach creation as a process of research and discovery.')),
                ('value2_label', models.CharField(default='Memory & the Body', max_length=100)),
                ('value2_text', models.TextField(blank=True, default='Influenced by contemporary performance, choreography, cinema, and documentary practices, we are interested in memory, spectatorship, the body, and the ways personal experience intersects with larger social and political realities.')),
                ('value3_label', models.CharField(default='International Exchange', max_length=100)),
                ('value3_text', models.TextField(blank=True, default='Through performances, films, workshops, and artistic laboratories, the studio creates spaces for encounter, exchange, and creative risk-taking, connecting contemporary artistic voices across different geographies, disciplines, and communities.')),
                ('cta_heading', models.CharField(default='Interested in presenting our work?', max_length=200)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
