# Generated by Django 6.0 on 2026-06-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_about_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='homephoto',
            name='home_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.homepage'),
        ),
    ]
