# Generated by Django 6.0 on 2026-06-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homephoto_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(blank=True, default="We're interested in hearing from presenters, festivals, venues, and press. Fill out the form and we'll get back to you shortly.")),
                ('booking_desc', models.TextField(blank=True, default='Festivals, venues, and presenters interested in hosting a production or commissioning new work.')),
                ('press_desc', models.TextField(blank=True, default='Media inquiries, interviews, and press accreditation for upcoming performances.')),
                ('general_desc', models.TextField(blank=True, default='Collaborations, residencies, and anything in between.')),
                ('location', models.CharField(blank=True, default='Toronto, Canada', max_length=200)),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
        ),
    ]
